In [1]:
import numpy as np
import pandas as pd
import scipy

import matplotlib.pyplot as plt
from matplotlib import rcParams
import seaborn as sb

import sklearn
from sklearn import preprocessing
from sklearn.preprocessing import scale

### Normalisation and Standardisation

In [14]:
df = pd.read_csv('cleaned.csv')
df

height  width  aratio  local  url*images+buttons:  url*likesbooks.com:  \
0      125.0  125.0  1.0000      1                    0                    0   
1       57.0  468.0  8.2105      1                    0                    0   
2       33.0  230.0  6.9696      1                    0                    0   
3       60.0  468.0  7.8000      1                    0                    0   
4       60.0  468.0  7.8000      1                    0                    0   
...      ...    ...     ...    ...                  ...                  ...   
2434    30.0   30.0  1.0000      0                    0                    0   
2435   170.0   94.0  0.5529      0                    0                    0   
2436   101.0  140.0  1.3861      1                    0                    0   
2437    23.0  120.0  5.2173      1                    0                    0   
2438    40.0   40.0  1.0000      1                    0                    0   

      url*www.slake.com:  url*hydrogeologist:  url*oso:  url*media:  ...  \
0                      0                    0         0           0  ...   
1                      0                    0         0           0  ...   
2                      0                    0         0           0  ...   
3                      0                    0         0           0  ...   
4                      0                    0         0           0  ...   
...                  ...                  ...       ...         ...  ...   
2434                   0                    0         0           0  ...   
2435                   0                    0         0           0  ...   
2436                   0                    0         0           0  ...   
2437                   0                    0         0           0  ...   
2438                   0                    0         0           0  ...   

      caption*home:  caption*my:  caption*your:  caption*in:  caption*bytes:  \
0                 0            0              0            0               0   
1                 0            0              0            0               0   
2                 0            0              0            0               0   
3                 0            0              0            0               0   
4                 0            0              0            0               0   
...             ...          ...            ...          ...             ...   
2434              0            0              0            0               0   
2435              0            0              0            0               0   
2436              0            0              0            0               0   
2437              0            0              0            0               0   
2438              0            0              0            0               0   

      caption*here:  caption*click:  caption*for:  caption*you:   class  
0                 0               0             0             0     ad.  
1                 0               0             0             0     ad.  
2                 0               0             0             0     ad.  
3                 0               0             0             0     ad.  
4                 0               0             0             0     ad.  
...             ...             ...           ...           ...     ...  
2434              0               0             0             0  nonad.  
2435              0               0             0             0  nonad.  
2436              0               0             0             0  nonad.  
2437              0               0             0             0  nonad.  
2438              0               0             0             0  nonad.  

[2439 rows x 1559 columns]

In [27]:
h = df['height']  # apply on one column
X = h.values.reshape(-1, 1)  # get the 1,2,3,4 columns and reshape the value to make it a 1x N  matrix
nf = preprocessing.MinMaxScaler()
r = nf.fit_transform(X)

In [16]:
X

array([[125.],
       [ 57.],
       [ 33.],
       ...,
       [101.],
       [ 23.],
       [ 40.]])

In [17]:
h

0       125.0
1        57.0
2        33.0
3        60.0
4        60.0
        ...  
2434     30.0
2435    170.0
2436    101.0
2437     23.0
2438     40.0
Name: height, Length: 2439, dtype: float64

In [26]:
r

array([[0.19405321],
       [0.08763693],
       [0.05007825],
       ...,
       [0.15649452],
       [0.03442879],
       [0.06103286]])

In [28]:
df1 = df.values  # apply on the whole data
df2 = df1[:, 0:1558]
df2_nor = nf.fit_transform(df2)

In [29]:
df2_nor


array([[0.19405321, 0.19405321, 0.01664208, ..., 0.        , 0.        ,
        0.        ],
       [0.08763693, 0.73082942, 0.13682009, ..., 0.        , 0.        ,
        0.        ],
       [0.05007825, 0.35837246, 0.1161379 , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.15649452, 0.21752739, 0.02307724, ..., 0.        , 0.        ,
        0.        ],
       [0.03442879, 0.18622848, 0.08693217, ..., 0.        , 0.        ,
        0.        ],
       [0.06103286, 0.06103286, 0.01664208, ..., 0.        , 0.        ,
        0.        ]])

In [24]:
nls = preprocessing.normalize(df2)  # another function which is recommended in ML Master

In [25]:
nls

array([[0.70693714, 0.70693714, 0.0056555 , ..., 0.        , 0.        ,
        0.        ],
       [0.12088013, 0.99248947, 0.01741204, ..., 0.        , 0.        ,
        0.        ],
       [0.14193112, 0.98921689, 0.02997585, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.58495049, 0.81082246, 0.00802772, ..., 0.        , 0.        ,
        0.        ],
       [0.18799975, 0.98086824, 0.0426457 , ..., 0.        , 0.        ,
        0.        ],
       [0.70589457, 0.70589457, 0.01764736, ..., 0.        , 0.        ,
        0.        ]])

### Standardise

In [30]:
sts = preprocessing.scale(df2)

In [31]:
sts

array([[ 1.12659818, -0.23919343, -0.48125431, ..., -0.12580437,
        -0.10380255, -0.02864753],
       [-0.13011467,  2.4393016 ,  0.73022359, ..., -0.12580437,
        -0.10380255, -0.02864753],
       [-0.57366038,  0.58075403,  0.52173278, ..., -0.12580437,
        -0.10380255, -0.02864753],
       ...,
       [ 0.68305247, -0.12205808, -0.41638342, ..., -0.12580437,
        -0.10380255, -0.02864753],
       [-0.75847109, -0.27823855,  0.2273187 , ..., -0.12580437,
        -0.10380255, -0.02864753],
       [-0.44429288, -0.90296042, -0.48125431, ..., -0.12580437,
        -0.10380255, -0.02864753]])